spring:
  application:
    name: server
  datasource:
    #    url: jdbc:sqlserver://cs544.cs.miu.edu:1433;databaseName=AdventureWorks2019
    url: jdbc:sqlserver://10.1.80.150:1433;databaseName=AdventureWorks2019
    username: adventure
    password: AdventureWorks
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

spring:
  application:
    name: flightreservation
  datasource:
    url: jdbc:mysql://localhost:3306/flightreservation
    username: root

    password: Itguykashi1!

    driverClassName: com.mysql.cj.jdbc.Driver

    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true

    generate-ddl: true

    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:

        dialect: org.hibernate.dialect.MySQL57Dialect
logging:
  file:


